name: Build and Deploy to S3

on:
  push:
    branches:
    - main

jobs:
  deploy:
    defaults:
      run:
        working-directory: '.'
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Generate prisma types
      run: npm run prisma-generate

    - name: Build
      run: npm run build

    - name: Copy files
      run: mv ./dist/yakkai-player/browser/* ./dist/yakkai-player/

    - name: Deploy
      if: success()
      run: aws s3 sync ./dist/yakkai-player/ s3://play.blackcompany.tv --delete

